# Generated by Django 4.1 on 2022-10-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='bg1.png', null=True, upload_to=''),
        ),
    ]
