# Generated by Django 4.1 on 2022-10-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Links',
            field=models.TextField(null=True),
        ),
    ]
