# Generated by Django 4.1 on 2022-10-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='LinkTitle',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
