# Generated by Django 4.1 on 2022-10-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_linktitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='FinalQuote',
            field=models.TextField(null=True),
        ),
    ]
